# Generated by Django 3.2 on 2024-06-18
from django.db import migrations, models


def set_default_roles(apps, schema_editor):
    Organization = apps.get_model('organizations', 'Organization')
    OrganizationMember = apps.get_model('organizations', 'OrganizationMember')

    ROLE_OWNER = 'OW'
    ROLE_READ_ONLY = 'RO'

    # Ensure every organization has a default role
    for org in Organization.objects.all():
        if not org.default_role:
            org.default_role = ROLE_READ_ONLY
            org.save(update_fields=['default_role'])

        # Promote creator to owner role
        if org.created_by_id:
            OrganizationMember.objects.filter(user_id=org.created_by_id, organization_id=org.id).update(
                role=ROLE_OWNER
            )

    # Any remaining memberships without a role should be read-only
    OrganizationMember.objects.filter(role__isnull=True).update(role=ROLE_READ_ONLY)


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20210310_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_role',
            field=models.CharField(
                choices=[
                    ('OW', 'Owner'),
                    ('AD', 'Administrator'),
                    ('AN', 'Annotator'),
                    ('RE', 'Reviewer'),
                    ('RO', 'Read Only'),
                    ('NO', 'Not Activated'),
                    ('DI', 'Deactivated'),
                ],
                default='RO',
                help_text='Default membership role for invited users',
                max_length=3,
                verbose_name='default role',
            ),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(
                choices=[
                    ('OW', 'Owner'),
                    ('AD', 'Administrator'),
                    ('AN', 'Annotator'),
                    ('RE', 'Reviewer'),
                    ('RO', 'Read Only'),
                    ('NO', 'Not Activated'),
                    ('DI', 'Deactivated'),
                ],
                default='RO',
                help_text='Organization membership role',
                max_length=3,
                verbose_name='role',
            ),
        ),
        migrations.RunPython(set_default_roles, migrations.RunPython.noop),
    ]
